

services:
  server:
    container_name: server
    build:
      context: ..
      dockerfile: config/Dockerfile.server
    sysctls:
      - net.ipv4.conf.all.arp_accept=1
    networks:
      lucky_lan: 
        ipv4_address: 192.168.100.10

  client:
    container_name: client
    build:
      context: ..
      dockerfile: config/Dockerfile.client
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.arp_accept=1
    networks:
      lucky_lan:
        ipv4_address: 192.168.100.20
    depends_on:
      - server 


  proxy:
    container_name: proxy
    build:
      context: ..
      dockerfile: config/Dockerfile.proxy
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      lucky_lan:
        ipv4_address: 192.168.100.30

networks:
  lucky_lan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24


